name: secrets and variables

on: 
  workflow_dispatch:

jobs:
  secrets and varaibles:
     runs-on: ubuntu-latest

     steps:
      - name: print repo secrets and variables
        run: echo "MY_SECRET is ${{ SECRET_DEMO_DEVOPS_06_2026 }}" && echo "MY_VARIABLE is ${{ VARIABLES_DEMO DEVOPS_06_2026 }}"