name: secrets and variables

on: 
  workflow_dispatch:

jobs:
  secrets_and_varaibles:
     runs-on: ubuntu-latest

     steps:
      - name: print repo secrets and variables
        run: echo "MY_SECRET is ${{ secrets.SECRET_DEMO_DEVOPS_06_2026 }}" && echo "MY_VARIABLE is ${{ vars.VARIABLES_DEMO }}"