name: variables

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'run environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod   
          - test   

      version:
        description: 'Application version'
        required: true
        default: "v1.0.0"    

env:     
  GLOBAL_ENV: " 1 Tire App"

jobs:
    job1:
      runs-on: ubuntu-latest
      env: 
        JOB1_ENV: "Something"
      steps:
        - name: Display Inputs
          run: |
            echo "Environment: ${{ env.GLOBAL_ENV }}"
            echo "Version: ${{ inputs.version }}"

        - name: Global Environment Variable
          run: |
            echo "Global Environment Variable: $GLOBAL_ENV"
 
        - name: job1 environemnt varaible
          run: |
            echo "Environment Variable: $JOB1_ENV"

    job2:
      runs-on: ubuntu-latest
      env: 
        JOB2_ENV: "Monolithic"
      steps:
        - name: Environment variale
          run: |
            echo "Environment Variable: $JOB2_ENV"